import { Item, ItemType } from '@/types/item';
import { SpriteID } from './sprite';

export const BASE_ITEM: Item = {
  id: '',
  type: ItemType.WEAPON,
  name: '',
  description: '',
  power: 0,
  speed: 0,
  health: 0,
  spriteID: SpriteID.T1_DAGGER,
  cost: 0,
  createdAt: new Date(),
};

const currentDate = new Date();

export const MOCK_ITEMS: Item[] = [
  // Tier 1 items
  {
    id: 't1_dagger',
    type: ItemType.WEAPON,
    name: 'T1 Dagger',
    description:
      "Small but mighty! Perfect for poking holes in your enemies' plans.",
    power: 5,
    speed: 10,
    health: 0,
    spriteID: SpriteID.T1_DAGGER,
    cost: 50,
    createdAt: currentDate,
  },
  {
    id: 't1_heavy_armor',
    type: ItemType.ARMOR,
    name: 'T1 Heavy Armor',
    description:
      'Clunky but dependable. Prepare for a slow, fashionable entrance.',
    power: 0,
    speed: -2,
    health: 10,
    spriteID: SpriteID.T1_HEAVY_ARMOR,
    cost: 100,
    createdAt: currentDate,
  },
  {
    id: 't1_helm',
    type: ItemType.ACCESSORY,
    name: 'T1 Helm',
    description:
      'Keeps your head safe and your dignity questionable. Better safe than sorry!',
    power: 0,
    speed: 0,
    health: 5,
    spriteID: SpriteID.T1_HELM,
    cost: 40,
    createdAt: currentDate,
  },
  {
    id: 't1_shield',
    type: ItemType.ACCESSORY,
    name: 'T1 Shield',
    description: 'Ideal for blocking unwanted blows... and conversations.',
    power: 2,
    speed: -1,
    health: 7,
    spriteID: SpriteID.T1_SHIELD,
    cost: 70,
    createdAt: currentDate,
  },
  {
    id: 't1_sword',
    type: ItemType.WEAPON,
    name: 'T1 Sword',
    description:
      'Simple but effective. Cuts down foes and keeps things classy.',
    power: 7,
    speed: 5,
    health: 0,
    spriteID: SpriteID.T1_SWORD,
    cost: 60,
    createdAt: currentDate,
  },

  // Tier 2 items
  {
    id: 't2_dagger',
    type: ItemType.WEAPON,
    name: 'T2 Dagger',
    description:
      'Sharper, faster, and guaranteed to make you look like a sneaky pro.',
    power: 10,
    speed: 12,
    health: 0,
    spriteID: SpriteID.T2_DAGGER,
    cost: 80,
    createdAt: currentDate,
  },
  {
    id: 't2_heavy_armor',
    type: ItemType.ARMOR,
    name: 'T2 Heavy Armor',
    description:
      'For when you want to feel like a tank and look twice as intimidating.',
    power: 0,
    speed: -3,
    health: 15,
    spriteID: SpriteID.T2_HEAVY_ARMOR,
    cost: 150,
    createdAt: currentDate,
  },
  {
    id: 't2_helm',
    type: ItemType.ACCESSORY,
    name: 'T2 Helm',
    description:
      'Enhanced protection and style. Perfect for those "knight in shining armor" vibes.',
    power: 0,
    speed: 0,
    health: 7,
    spriteID: SpriteID.T2_HELM,
    cost: 70,
    createdAt: currentDate,
  },
  {
    id: 't2_shield',
    type: ItemType.ACCESSORY,
    name: 'T2 Shield',
    description:
      'Deflects attacks and doubles as a mirror for quick armor checks.',
    power: 3,
    speed: -1,
    health: 10,
    spriteID: SpriteID.T2_SHIELD,
    cost: 90,
    createdAt: currentDate,
  },
  {
    id: 't2_sword',
    type: ItemType.WEAPON,
    name: 'T2 Sword',
    description:
      'Sharper, deadlier, and just classy enough to keep things civil.',
    power: 12,
    speed: 6,
    health: 0,
    spriteID: SpriteID.T2_SWORD,
    cost: 110,
    createdAt: currentDate,
  },

  {
    id: 'health_potion_small',
    type: ItemType.POTION_SMALL,
    name: 'Small Health Potion',
    description: 'Heals 10% of max health. A sip-sized fix for small troubles.',
    power: 0,
    speed: 0,
    health: 0,
    cost: 50,
    spriteID: SpriteID.HEALTH_POTION_SMALL,
    createdAt: currentDate,
  },
  {
    id: 'health_potion_medium',
    type: ItemType.POTION_MEDIUM,
    name: 'Medium Health Potion',
    description:
      'Heals 15% of max health. For those medium-level problems in life (and death).',
    power: 0,
    speed: 0,
    health: 0,
    cost: 75,
    spriteID: SpriteID.HEALTH_POTION_MEDIUM,
    createdAt: currentDate,
  },
  {
    id: 'health_potion_large',
    type: ItemType.POTION_LARGE,
    name: 'Large Health Potion',
    description: 'Heals 20% of max health. A full dose of "not today, death!"',
    power: 0,
    speed: 0,
    health: 0,
    cost: 100,
    spriteID: SpriteID.HEALTH_POTION_LARGE,
    createdAt: currentDate,
  },
];
