import { Item, ItemType } from '@/types/item';

const currentDate = new Date();

export const MOCK_SHOP_ITEMS: Item[] = [
  {
    id: 'fesfsgggdes',
    type: ItemType.WEAPON,
    name: 'Sword',
    description: 'Sharp enough to solve most problems, but not all of them.',
    power: 10,
    speed: 7,
    health: 0,
    cost: 50,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'fsgfargergghs',
    type: ItemType.WEAPON,
    name: 'Axe',
    description: "For when subtlety just isn't in your vocabulary.",
    power: 15,
    speed: 5,
    health: 0,
    cost: 75,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'y4ejrtasg',
    type: ItemType.WEAPON,
    name: 'Short Bow',
    description: "Ideal for hitting things you don't want to get too close to.",
    power: 10,
    speed: 7,
    health: 3,
    cost: 75,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'gdsgsdg',
    type: ItemType.WEAPON,
    name: 'Long Bow',
    description: "Turns 'social distancing' into an art form.",
    power: 20,
    speed: 1,
    health: 0,
    cost: 75,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'hdhthtrjj',
    type: ItemType.ARMOR,
    name: 'Leather Armor',
    description: 'Soft on comfort, light on life-saving durability.',
    power: 0,
    speed: 2,
    health: 10,
    cost: 50,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'rjrjt',
    type: ItemType.ARMOR,
    name: 'Chainmail Armor',
    description: 'Adds just enough jingle to scare off silent approaches.',
    power: 0,
    speed: 10,
    health: 10,
    cost: 75,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'gw5ye3he5h',
    type: ItemType.ARMOR,
    name: 'Steel Armor',
    description: 'Feels like a hug… from a very heavy robot.',
    power: 0,
    speed: 5,
    health: 15,
    cost: 100,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'rherheb',
    type: ItemType.ACCESSORY,
    name: 'Rock Pendant',
    description: 'Solid, dependable, and guaranteed to be hard as a rock.',
    power: 5,
    speed: 0,
    health: 5,
    cost: 100,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'afea4twegwerg',
    type: ItemType.ACCESSORY,
    name: 'Fire Pendant',
    description: 'Adds a little heat to your style… and maybe your enemies.',
    power: 5,
    speed: 5,
    health: 0,
    cost: 100,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'gssgsgsgs',
    type: ItemType.POTION_SMALL,
    name: 'Small Health Potion',
    description: 'Heals 10% of max health. A sip-sized fix for small troubles.',
    power: 0,
    speed: 0,
    health: 0,
    cost: 50,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'gssgsgsgsdsfs',
    type: ItemType.POTION_MEDIUM,
    name: 'Medium Health Potion',
    description:
      'Heals 15% of max health. For those medium-level problems in life (and death).',
    power: 0,
    speed: 0,
    health: 0,
    cost: 75,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'gssgfsfsasgsgs',
    type: ItemType.POTION_LARGE,
    name: 'Large Health Potion',
    description: "Heals 20% of max health. A full dose of 'not today, death!'",
    power: 0,
    speed: 0,
    health: 0,
    cost: 100,
    spriteID: 'sword',
    createdAt: currentDate,
  },
];
