import { Item, ItemType } from '@/types/item';

const currentDate = new Date();

export const MOCK_SHOP_ITEMS: Item[] = [
  // Tier 1 items
  {
    id: 't1_dagger',
    type: ItemType.WEAPON,
    name: 'T1 Dagger',
    description: 'A simple dagger with a sharp point.',
    power: 5,
    speed: 10,
    health: 0,
    spriteID: 't1_dagger',
    cost: 50,
    createdAt: currentDate,
  },
  {
    id: 't1_heavy_armor',
    type: ItemType.ARMOR,
    name: 'T1 Heavy Armor',
    description: 'Basic heavy armor, offers solid protection.',
    power: 0,
    speed: -2,
    health: 10,
    spriteID: 't1_heavy_armor',
    cost: 100,
    createdAt: currentDate,
  },
  {
    id: 't1_helm',
    type: ItemType.ACCESSORY,
    name: 'T1 Helm',
    description: 'A simple helm, offering basic head protection.',
    power: 0,
    speed: 0,
    health: 5,
    spriteID: 't1_helm',
    cost: 40,
    createdAt: currentDate,
  },
  {
    id: 't1_shield',
    type: ItemType.ACCESSORY,
    name: 'T1 Shield',
    description: 'A basic shield, useful for blocking attacks.',
    power: 2,
    speed: -1,
    health: 7,
    spriteID: 't1_shield',
    cost: 70,
    createdAt: currentDate,
  },
  {
    id: 't1_sword',
    type: ItemType.WEAPON,
    name: 'T1 Sword',
    description: 'A standard sword for close combat.',
    power: 7,
    speed: 5,
    health: 0,
    spriteID: 't1_sword',
    cost: 60,
    createdAt: currentDate,
  },

  // Tier 2 items
  {
    id: 't2_dagger',
    type: ItemType.WEAPON,
    name: 'T2 Dagger',
    description: 'A sharper and more durable dagger.',
    power: 10,
    speed: 12,
    health: 0,
    spriteID: 't2_dagger',
    cost: 80,
    createdAt: currentDate,
  },
  {
    id: 't2_heavy_armor',
    type: ItemType.ARMOR,
    name: 'T2 Heavy Armor',
    description: 'Enhanced heavy armor for better protection.',
    power: 0,
    speed: -3,
    health: 15,
    spriteID: 't2_heavy_armor',
    cost: 150,
    createdAt: currentDate,
  },
  {
    id: 't2_helm',
    type: ItemType.ACCESSORY,
    name: 'T2 Helm',
    description: 'A stronger helm with improved defense.',
    power: 0,
    speed: 0,
    health: 7,
    spriteID: 't2_helm',
    cost: 70,
    createdAt: currentDate,
  },
  {
    id: 't2_shield',
    type: ItemType.ACCESSORY,
    name: 'T2 Shield',
    description: 'A sturdier shield with increased durability.',
    power: 3,
    speed: -1,
    health: 10,
    spriteID: 't2_shield',
    cost: 90,
    createdAt: currentDate,
  },
  {
    id: 't2_sword',
    type: ItemType.WEAPON,
    name: 'T2 Sword',
    description: 'A sharper sword for more effective combat.',
    power: 12,
    speed: 6,
    health: 0,
    spriteID: 't2_sword',
    cost: 110,
    createdAt: currentDate,
  },
  {
    id: 'hpot_small',
    type: ItemType.POTION_SMALL,
    name: 'Small Health Potion',
    description: 'Heals 10% of max health. A sip-sized fix for small troubles.',
    power: 0,
    speed: 0,
    health: 0,
    cost: 50,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'hpot_medium',
    type: ItemType.POTION_MEDIUM,
    name: 'Medium Health Potion',
    description:
      'Heals 15% of max health. For those medium-level problems in life (and death).',
    power: 0,
    speed: 0,
    health: 0,
    cost: 75,
    spriteID: 'sword',
    createdAt: currentDate,
  },
  {
    id: 'hpot_large',
    type: ItemType.POTION_LARGE,
    name: 'Large Health Potion',
    description: "Heals 20% of max health. A full dose of 'not today, death!'",
    power: 0,
    speed: 0,
    health: 0,
    cost: 100,
    spriteID: 'sword',
    createdAt: currentDate,
  },
];
