import {
  Exercise,
  ExerciseDisplay,
  ExerciseTag,
  Workout,
} from '@/types/workout';

export const BASE_EXERCISE_DISPLAY: ExerciseDisplay = {
  id: '',
  name: '',
  muscleGroup: '',
  tags: [],
  sets: [],
};

export const BASE_EXERCISE_SET_DISPLAY = {
  id: '',
  weight: 0,
  reps: 0,
  distance: 0,
  time: 0,
  completed: false,
};

export enum MuscleGroup {
  CHEST = 'Chest',
  BACK = 'Back',
  ARMS = 'Arms',
  SHOULDERS = 'Shoulders',
  LEGS = 'Legs',
  CORE = 'Core',
  CARDIO = 'Cardio',
}

export const EXERCISES_STUB: Exercise[] = [
  {
    id: '3234',
    name: 'Bench Press',
    muscleGroup: 'Chest',
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [
      {
        id: 'garg',
        weight: 100,
        reps: 10,
        distance: 0,
        time: 0,
      },
      {
        id: 'arga',
        weight: 100,
        reps: 8,
        distance: 0,
        time: 0,
      },
    ],
  },
  {
    id: '254',
    name: 'Jogging',
    muscleGroup: 'Cardio',
    tags: [ExerciseTag.DISTANCE, ExerciseTag.TIME],
    sets: [
      {
        id: 'gsg',
        weight: 0,
        reps: 0,
        distance: 5,
        time: 30,
      },
      {
        id: 'hdfh',
        weight: 0,
        reps: 0,
        distance: 5,
        time: 30,
      },
    ],
  },
];

export const ALL_EXERCISES_STUB: Exercise[] = [
  // CHEST
  {
    id: '',
    name: 'Bench Press',
    muscleGroup: MuscleGroup.CHEST,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Incline Bench Press',
    muscleGroup: MuscleGroup.CHEST,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Decline Bench Press',
    muscleGroup: MuscleGroup.CHEST,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Push Up',
    muscleGroup: MuscleGroup.CHEST,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Chest Dip',
    muscleGroup: MuscleGroup.CHEST,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },

  // BACK
  {
    id: '',
    name: 'Deadlift',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Lat Pulldown',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Row (Barbell)',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Row (Dumbbell)',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Pull Up',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Chin Up',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Inverted Row',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Shrug',
    muscleGroup: MuscleGroup.BACK,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },

  // ARMS
  {
    id: '',
    name: 'Bicep Curl',
    muscleGroup: MuscleGroup.ARMS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Tricep Extension',
    muscleGroup: MuscleGroup.ARMS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Hammer Curl',
    muscleGroup: MuscleGroup.ARMS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Tricep Dip',
    muscleGroup: MuscleGroup.ARMS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Skull Crusher',
    muscleGroup: MuscleGroup.ARMS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },

  // SHOULDERS
  {
    id: '',
    name: 'Shoulder Press (Barbell)',
    muscleGroup: MuscleGroup.SHOULDERS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Shoulder Press (Dumbbell)',
    muscleGroup: MuscleGroup.SHOULDERS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Lateral Raise',
    muscleGroup: MuscleGroup.SHOULDERS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Front Raise',
    muscleGroup: MuscleGroup.SHOULDERS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Rear Delt Fly',
    muscleGroup: MuscleGroup.SHOULDERS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },

  // LEGS
  {
    id: '',
    name: 'Squat',
    muscleGroup: MuscleGroup.LEGS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Lunge',
    muscleGroup: MuscleGroup.LEGS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Pistol Squat',
    muscleGroup: MuscleGroup.LEGS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Leg Press',
    muscleGroup: MuscleGroup.LEGS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Leg Extension',
    muscleGroup: MuscleGroup.LEGS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Leg Curl',
    muscleGroup: MuscleGroup.LEGS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Calf Raise',
    muscleGroup: MuscleGroup.LEGS,
    tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
    sets: [],
  },

  // Core
  {
    id: '',
    name: 'Plank',
    muscleGroup: MuscleGroup.CORE,
    tags: [ExerciseTag.TIME],
    sets: [],
  },
  {
    id: '',
    name: 'Sit Up',
    muscleGroup: MuscleGroup.CORE,
    tags: [ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Russian Twist',
    muscleGroup: MuscleGroup.CORE,
    tags: [ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Ab Wheel Rollout (Assisted)',
    muscleGroup: MuscleGroup.CORE,
    tags: [ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Ab Wheel Rollout',
    muscleGroup: MuscleGroup.CORE,
    tags: [ExerciseTag.REPS],
    sets: [],
  },
  {
    id: '',
    name: 'Dragon Flag',
    muscleGroup: MuscleGroup.CORE,
    tags: [ExerciseTag.REPS],
    sets: [],
  },

  // Cardio
  {
    id: '',
    name: 'Walking',
    muscleGroup: MuscleGroup.CARDIO,
    tags: [ExerciseTag.DISTANCE, ExerciseTag.TIME],
    sets: [],
  },
  {
    id: '',
    name: 'Jogging',
    muscleGroup: MuscleGroup.CARDIO,
    tags: [ExerciseTag.DISTANCE, ExerciseTag.TIME],
    sets: [],
  },
  {
    id: '',
    name: 'Cycling',
    muscleGroup: MuscleGroup.CARDIO,
    tags: [ExerciseTag.DISTANCE, ExerciseTag.TIME],
    sets: [],
  },
  {
    id: '',
    name: 'Swimming',
    muscleGroup: MuscleGroup.CARDIO,
    tags: [ExerciseTag.DISTANCE, ExerciseTag.TIME],
    sets: [],
  },
  {
    id: '',
    name: 'Burpee',
    muscleGroup: MuscleGroup.CARDIO,
    tags: [ExerciseTag.TIME],
    sets: [],
  },
  {
    id: '',
    name: 'Jump Rope',
    muscleGroup: MuscleGroup.CARDIO,
    tags: [ExerciseTag.TIME],
    sets: [],
  },
  {
    id: '',
    name: 'Boxing',
    muscleGroup: MuscleGroup.CARDIO,
    tags: [ExerciseTag.TIME],
    sets: [],
  },
];

export const SUGGESTED_TEMPLATES: Workout[] = [
  {
    id: '-1',
    title: 'Heart Health',
    startedAt: new Date(),
    duration: 30,
    exercises: [
      {
        id: '0',
        name: 'Jogging',
        muscleGroup: 'Cardio',
        tags: [ExerciseTag.DISTANCE, ExerciseTag.TIME],
        sets: [
          {
            id: '0',
            weight: 0,
            reps: 0,
            distance: 1,
            time: 10,
          },
          {
            id: '1',
            weight: 0,
            reps: 0,
            distance: 1,
            time: 10,
          },
        ],
      },
      {
        id: '1',
        name: 'Jump Rope',
        muscleGroup: 'Cardio',
        tags: [ExerciseTag.TIME],
        sets: [
          {
            id: '0',
            weight: 0,
            reps: 0,
            distance: 0,
            time: 5,
          },
          {
            id: '1',
            weight: 0,
            reps: 0,
            distance: 0,
            time: 5,
          },
        ],
      },
      {
        id: '2',
        name: 'Walking',
        muscleGroup: 'Cardio',
        tags: [ExerciseTag.DISTANCE, ExerciseTag.TIME],
        sets: [
          {
            id: '0',
            weight: 0,
            reps: 0,
            distance: 1,
            time: 30,
          },
          {
            id: '1',
            weight: 0,
            reps: 0,
            distance: 1,
            time: 30,
          },
        ],
      },
    ],
  },
  {
    id: '0',
    title: 'Full Body Workout',
    startedAt: new Date(),
    duration: 60,
    exercises: [
      {
        id: '0',
        name: 'Squat',
        muscleGroup: 'Legs',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '0',
            weight: 225,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '1',
            weight: 225,
            reps: 8,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 225,
            reps: 6,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '1',
        name: 'Bench Press',
        muscleGroup: 'Chest',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '0',
            weight: 135,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '1',
            weight: 135,
            reps: 8,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 135,
            reps: 6,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '2',
        name: 'Deadlift',
        muscleGroup: 'Back',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '0',
            weight: 315,
            reps: 5,
            distance: 0,
            time: 0,
          },
          {
            id: '1',
            weight: 315,
            reps: 5,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 315,
            reps: 5,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '3',
        name: 'Shoulder Press',
        muscleGroup: 'Shoulders',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '0',
            weight: 135,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '1',
            weight: 135,
            reps: 8,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 135,
            reps: 6,
            distance: 0,
            time: 0,
          },
        ],
      },
    ],
  },
  {
    id: '1',
    title: 'Chest Day',
    startedAt: new Date(),
    duration: 60,
    exercises: [
      {
        id: '1',
        name: 'Bench Press',
        muscleGroup: 'Chest',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 225,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 225,
            reps: 8,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '2',
        name: 'Incline Bench Press',
        muscleGroup: 'Chest',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 185,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 185,
            reps: 8,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '3',
        name: 'Decline Bench Press',
        muscleGroup: 'Chest',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 185,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 185,
            reps: 8,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '4',
        name: 'Push Up',
        muscleGroup: 'Chest',
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 0,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 0,
            reps: 8,
            distance: 0,
            time: 0,
          },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'Back Day',
    startedAt: new Date(),
    duration: 60,
    exercises: [
      {
        id: '6',
        name: 'Deadlift',
        muscleGroup: MuscleGroup.BACK,
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 315,
            reps: 5,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 315,
            reps: 5,
            distance: 0,
            time: 0,
          },
          {
            id: '3',
            weight: 315,
            reps: 5,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '7',
        name: 'Lat Pulldown',
        muscleGroup: MuscleGroup.BACK,
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 135,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 135,
            reps: 8,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '8',
        name: 'Row (Barbell)',
        muscleGroup: MuscleGroup.BACK,
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 135,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 135,
            reps: 8,
            distance: 0,
            time: 0,
          },
        ],
      },
      {
        id: '10',
        name: 'Bicep Curl',
        muscleGroup: MuscleGroup.ARMS,
        tags: [ExerciseTag.WEIGHT, ExerciseTag.REPS],
        sets: [
          {
            id: '1',
            weight: 35,
            reps: 10,
            distance: 0,
            time: 0,
          },
          {
            id: '2',
            weight: 35,
            reps: 8,
            distance: 0,
            time: 0,
          },
        ],
      },
    ],
  },
];
